export * from './getRandom'
export * from './getDimensions'
export * from './getColorString'
export * from './getRandomColor'
export * from './getColorIncrement'
export * from './getFilledSquares'
export * from './handleLocalStorage'
